site_name: Tulipan
site_description: 'Documentation for Tulipan.js, a simple and progressive, JavaScript Framework for building Single Page Applications on the web.'
site_url: 'http://tulipan-documentation.readthedocs.io'
site_author: https://github.com/carrasquel/tulipan-documentation/graphs/contributors
repo_url: http://github.com/carrasquel/tulipan
remote_branch: master
nav:
  - Home: index.md
  - Getting Started: started.md
  - Bindings: bindings.md
  - Renderings: renderings.md
  - Filters: filters.md
  - Web Requests: requests.md
  - Routing: routing.md
  - Storing: storing.md

theme: 
  name: material

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/tulipan.min.js
  - javascripts/demo.js
  - javascripts/book.js

extra:
  social:
    - type: 'github'
      link: 'https://github.com/carrasquel'

google_analytics:
  - 'UA-125411854-3'
  - 'auto'

plugins:
    - pdf-export:
        combined: true

markdown_extensions:
  - codehilite