site_name: Tulipan
site_description: 'Documentation for Tulipan.js, a simple and progressive, JavaScript Framework for building Single Page Applications on the web.'
site_url: 'http://tulipan-framework.rtfd.io/'
site_author: https://github.com/carrasquel/tulipan-documentation/graphs/contributors
repo_url: http://github.com/carrasquel/tulipan
remote_branch: master
nav:
  - Home: index.md
  - Getting Started: cli.md

theme: material

extra:
  social:
    - type: 'github'
      link: 'https://github.com/carrasquel'

google_analytics:
  - 'UA-125411854-3'
  - 'auto'

markdown_extensions:
  - codehilite

